# Generated by Django 2.1.2 on 2018-11-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_storage', models.CharField(max_length=1)),
                ('is_presentation', models.CharField(max_length=1)),
                ('is_application', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='datalin.Node')),
                ('owner_name', models.CharField(max_length=255, null=True)),
                ('contact_email', models.CharField(max_length=255, null=True)),
                ('is_bi', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='node_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_a', to='datalin.Node'),
        ),
        migrations.AddField(
            model_name='relation',
            name='node_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_b', to='datalin.Node'),
        ),
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Relation_Type'),
        ),
        migrations.AddField(
            model_name='node',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalin.Technology'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('node_a', 'relation_type', 'node_b')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('short_name', 'technology')},
        ),
    ]
