# Generated by Django 2.1.2 on 2018-10-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('is_bi', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Technology'),
        ),
    ]
