# Generated by Django 2.1.2 on 2018-10-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_a', to='datalin.Node')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_b', to='datalin.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='application',
        ),
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Relation_Type'),
        ),
        migrations.AddField(
            model_name='node',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalin.Entity'),
        ),
    ]
