# Generated by Django 2.1.2 on 2018-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0002_auto_20181114_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
