# Generated by Django 2.1.2 on 2018-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0004_auto_20181028_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='relation_type',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='short_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('short_name', 'technology')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'entity', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('node_a', 'relation_type', 'node_b')},
        ),
    ]
