# Generated by Django 2.1.2 on 2018-12-13 09:42

from django.db import migrations

def insert_relation_type(apps, schema_editor):
    Relation_Type = apps.get_model('datalin', 'Relation_Type')
    Relation_Type.objects.all().delete()
    relation_type = Relation_Type(name='absorbs', description='takes data from')
    relation_type.save()
    relation_type = Relation_Type(name='belongs to', description='is part of')
    relation_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0004_auto_20181213_1040'),
    ]

    operations = [
        migrations.RunPython(insert_relation_type),
    ]
