# Generated by Django 2.1.2 on 2018-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0005_auto_20181029_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_presentation',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='is_storage',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
