# Generated by Django 2.1.2 on 2019-03-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0006_applicationload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationLoad',
            new_name='Application_Load',
        ),
    ]
