# Generated by Django 2.1.2 on 2018-10-29 13:36

from django.db import migrations

def insert_technolofy(apps, schema_editor):
    Technology = apps.get_model('datalin', 'Technology')
    Technology.objects.all().delete()
    technology = Technology(short_name='Netezza', name='Netezza', provider='IBM')
    technology.save()
    technology = Technology(short_name='BO', name='Business Objects', provider='SAP')
    technology.save()
    technology = Technology(short_name='MS SQL', name='SQL Server', provider='Microsoft')
    technology.save()
    technology = Technology(short_name='SSRS', name='SQL Server Reporting Services', provider='Microsoft')
    technology.save()
    technology = Technology(short_name='SSAS', name='SQL Server Analysis Services', provider='Microsoft')
    technology.save()
    technology = Technology(short_name='Oracle DB', name='Oracle Database', provider='Oracle')
    technology.save()

def insert_entity(apps, schema_editor):
    Entity = apps.get_model('datalin', 'Entity')
    Entity.objects.all().delete()
    Technology = apps.get_model('datalin', 'Technology')
    t = Technology.objects.get(short_name='Netezza')
    t.entity_set.create(short_name='DB', name='Database', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='T', name='Table', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='VW', name='View', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='SP', name='Stored Procedure', is_storage='Y', is_presentation='N')
    t.save()
    t = Technology.objects.get(short_name='BO')
    t.entity_set.create(short_name='Unv', name='Universe 3.X', is_storage='N', is_presentation='Y')
    t.entity_set.create(short_name='Unx', name='Universe 4', is_storage='N', is_presentation='Y')
    t.save()
    t = Technology.objects.get(short_name='MS SQL')
    t.entity_set.create(short_name='DB', name='Database', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='T', name='Table', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='VW', name='View', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='SP', name='Stored Procedure', is_storage='Y', is_presentation='N')
    t.save()
    t = Technology.objects.get(short_name='SSRS')
    t.entity_set.create(short_name='Rep', name='SSRS Report', is_storage='N', is_presentation='Y')
    t.entity_set.create(short_name='Con', name='SSRS Connection', is_storage='N', is_presentation='Y')
    t.save()
    t = Technology.objects.get(short_name='SSAS')
    t.entity_set.create(short_name='Cube', name='OLAP cube', is_storage='Y', is_presentation='N')
    t.save()
    t = Technology.objects.get(short_name='Oracle DB')
    t.entity_set.create(short_name='DB', name='Database', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='T', name='Table', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='VW', name='View', is_storage='Y', is_presentation='N')
    t.entity_set.create(short_name='SP', name='Stored Procedure', is_storage='Y', is_presentation='N')
    t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0006_auto_20181029_1436'),
    ]

    operations = [
        migrations.RunPython(insert_technolofy),
        migrations.RunPython(insert_entity),
    ]

