# Generated by Django 2.1.2 on 2019-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0007_auto_20190312_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_load',
            name='entity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
