# Generated by Django 2.1.2 on 2019-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0008_application_load_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_load',
            name='is_bi',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
