# Generated by Django 2.1.2 on 2019-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0009_auto_20190312_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('sql_operation', models.CharField(max_length=100, null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('row_count', models.IntegerField(null=True)),
                ('success_flag', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
