# Generated by Django 2.1.2 on 2019-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0010_load_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_log',
            name='load_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
