# Generated by Django 2.1.2 on 2019-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0011_load_log_load_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_log',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
