# Generated by Django 2.1.2 on 2019-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0012_auto_20190313_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load_log',
            name='duration',
        ),
        migrations.AddField(
            model_name='load_log',
            name='duration_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
