# Generated by Django 2.1.2 on 2019-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0013_auto_20190313_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('entity', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
