# Generated by Django 2.1.2 on 2019-03-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0014_node_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_load',
            name='technology',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
