# Generated by Django 2.1.2 on 2019-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0015_node_load_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_load',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
