# Generated by Django 2.1.2 on 2019-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0016_auto_20190313_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_a', models.CharField(max_length=255)),
                ('relation_type', models.CharField(max_length=30)),
                ('relation_level', models.IntegerField(default=1)),
                ('node_b', models.CharField(max_length=255)),
            ],
        ),
    ]
