# Generated by Django 2.1.2 on 2019-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0019_full_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='weigh',
            field=models.IntegerField(null=True),
        ),
    ]
