# Generated by Django 2.1.2 on 2019-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0020_entity_weigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='weigh',
            field=models.IntegerField(null=True),
        ),
    ]
