# Generated by Django 2.1.2 on 2019-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalin', '0021_node_weigh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='weigh',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='weigh',
            new_name='weight',
        ),
    ]
